import { NextIntlClientProvider, useMessages } from "next-intl";
import { getLocale } from "next-intl/server";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props  = {
  children: React.ReactNode;
  params: {

    locale: "en" | "es"

  }
}

const RootLayout: React.FC<Props> = ({ 
  children, 
  params: {locale}, 
}) => {

  const messages = useMessages();


  return (
    <html lang={locale}>
      <NextIntlClientProvider  messages={messages} >
      <body className={inter.className}>{children}</body>
      </NextIntlClientProvider>
      
    </html>
  );
}

export default RootLayout;
